version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    ports:
      - 5432:5432
    volumes:
      - ./.docker/pgdata:/data/postgres
    network_mode: "host"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
  app:
    container_name: rentx
    build: .
    ports:
      - 3333:3333
    network_mode: "host"
    volumes:
      - .:/usr/app
